### ISSUE TITLE
Test tutorial

### ISSUE THREAD

**Issue by spdegabrielle** [countvajhula/qi-template#1]
Ensure it works on different editors 

https://github.com/racket-templates/racket-templates/pull/3

**Comment by spdegabrielle** [comment]
When you wrote 
> Just open this file in your favorite editor, read through the comments, and evaluate each expression as you go.

do you mean stepping through the code with the [Graphical Debugging Interface](https://docs.racket-lang.org/drracket/debugger.html)?

![image](https://user-images.githubusercontent.com/108047/142758903-4bf9c352-374e-47ff-919e-3bb943a30853.png)

**Comment by countvajhula** [comment]
Using the debugger is a good idea, but it's a little more heavyweight than I had in mind. When you put your cursor next to an expression in DrRacket it highlights it. What I'd like is to be able to press a keyboard shortcut and that should evaluate the highlighted expression so that the result appears in the interactions window. This way we wouldn't need to enter and leave the debugger to try out experiments.

<img width="936" alt="Screen Shot 2021-11-21 at 9 26 36 AM" src="https://user-images.githubusercontent.com/401668/142772547-ef7c7f55-6555-4ed8-ba91-04d2c1e7eb8f.png">

In Emacs, the expression can be "sent to the REPL" using a keyboard shortcut, where the REPL is usually in a split pane.

<img width="1552" alt="Screen Shot 2021-11-21 at 9 18 03 AM" src="https://user-images.githubusercontent.com/401668/142772611-ce5c76d7-5cf3-4570-9c04-90e2d91f4447.png">

**Comment by spdegabrielle** [comment]
that would be easy to do with a custom quickscript to take the selection
and paste it into the interactions.

https://docs.racket-lang.org/quickscript/index.html#%28part._.Into_more_details%29

best wishes
Stephen

**Comment by countvajhula** [comment]
Ah nice. Can it also send the _highlighted_ expression to the interactions window? DrRacket highlights the current expression without needing to select anything.

**Comment by spdegabrielle** [comment]
that is an interesting question. 
quickscript has parameters to get the objects, and I think they are extended by the mixins in framework;
https://docs.racket-lang.org/framework/Text.html#%28def._%28%28lib._framework%2Fmain..rkt%29._text~3arange-color%29%29

Outa my depth here. Probably a question to ask on the discourse. (can you do it I'm trying to stay quiet)

> #:definitions : text%
> 
> The text% editor of the current definition window. See text% for more details.
> 
> #:interactions : text%
> 
> The text% editor of the current interaction window. Similar to #:definitions.
> 
> #:editor : text%
> 
> The text% current editor, either the definition or the interaction editor. Similar to #:definitions.
> 
> #:frame : drracket:unit:frame<%>
> 
> DrRacket’s frame. For advanced scripting.

**Comment by countvajhula** [comment]
No worries, I'll ask on Discourse. Thanks!

**Comment by countvajhula** [comment]
This now works great on DrRacket thanks to @Metaxal, so I think we're good here 👌
